name: Build and Deploy fqnovel-api

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust environment
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        profile: minimal

    - name: Install Dependencies
      run: cargo install -q worker-build

    - name: Build Worker
      run: worker-build --release

    - name: List Files in Build Directory
      run: ls -R target/release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: target/release
